

#ifndef _STM32_BOARD_DEFINE_
#define _STM32_BOARD_DEFINE_

#include <stm32_define.h>
#include "gpio.h"
#include "i2c.h"
#include "spi.h"
#include "usart.h"
#include "usb_device.h"

extern USBD_HandleTypeDef hUsbDeviceFS;

STM32_PIN_START(hi2c1)
    STM32_PIN(GPIOB,GPIO_PIN_6)     /* SCL */
    STM32_PIN(GPIOB,GPIO_PIN_7)     /* SDA */
STM32_PIN_END

STM32_PIN_START(hspi3)
    STM32_PIN(GPIOC,GPIO_PIN_10)
    STM32_PIN(GPIOC,GPIO_PIN_11)
    STM32_PIN(GPIOC,GPIO_PIN_12)
    STM32_PIN_NULL
STM32_PIN_END

#if 0

STM32_PIN_START(huart6)
    STM32_PIN(GPIOC,GPIO_PIN_6)
    STM32_PIN(GPIOC,GPIO_PIN_7)
STM32_PIN_END

#endif

STM32_PIN_START(hUsbDeviceFS)
    STM32_PIN(GPIOA,GPIO_PIN_11)
    STM32_PIN(GPIOA,GPIO_PIN_12)
STM32_PIN_END

//STM32_EXTRAM(ccm,32*1024,0x10000000)	/* F407 CCM address (Core Coupled Memory)*/


STM32_PIN_GPIO_START
    STM32_GPIO_PIN(HAL_PIN_07_GPIO,GPIOE,GPIO_PIN_3)
    STM32_GPIO_PIN(HAL_PIN_11_GPIO,GPIOE,GPIO_PIN_4)
    STM32_GPIO_PIN(HAL_PIN_12_GPIO,GPIOE,GPIO_PIN_6)
    STM32_GPIO_PIN(HAL_PIN_13_GPIO,GPIOE,GPIO_PIN_5)
    STM32_GPIO_PIN(HAL_PIN_15_GPIO,GPIOE,GPIO_PIN_0)
    STM32_GPIO_PIN(HAL_PIN_16_GPIO,GPIOE,GPIO_PIN_1)
    STM32_GPIO_PIN(HAL_PIN_18_GPIO,GPIOB,GPIO_PIN_9)
    STM32_GPIO_PIN(HAL_PIN_22_GPIO,GPIOE,GPIO_PIN_2)
    STM32_GPIO_PIN(HAL_PIN_24_NSS,GPIOA,GPIO_PIN_15)
    STM32_GPIO_PIN(HAL_PIN_26_GPIO,GPIOD,GPIO_PIN_0)
    STM32_GPIO_PIN(HAL_PIN_29_GPIO,GPIOD,GPIO_PIN_7)
    STM32_GPIO_PIN(HAL_PIN_31_GPIO,GPIOD,GPIO_PIN_2)
    STM32_GPIO_PIN(HAL_PIN_32_GPIO,GPIOD,GPIO_PIN_1)
    STM32_GPIO_PIN(HAL_PIN_33_GPIO,GPIOD,GPIO_PIN_6)
    STM32_GPIO_PIN(HAL_PIN_35_GPIO,GPIOD,GPIO_PIN_5)
    STM32_GPIO_PIN(HAL_PIN_36_GPIO,GPIOD,GPIO_PIN_3)
    STM32_GPIO_PIN(HAL_PIN_37_GPIO,GPIOD,GPIO_PIN_4)
    STM32_GPIO_PIN(HAL_PIN_38_GPIO,GPIOB,GPIO_PIN_8)
STM32_PIN_END

STM32_BOARD_START
    STM32_IP_I2C(hi2c1,MX_I2C1_Init)
    //STM32_IP_UART(huart6,MX_USART6_UART_Init)
    STM32_IP_GPIO(MX_GPIO_Init)
    STM32_IP_SPI(hspi3,MX_SPI3_Init)
    STM32_IP_BRIDGE_USB(hUsbDeviceFS,MX_USB_DEVICE_Init)
STM32_BOARD_END

#endif

